server:
  port: 8081

spring:
  jpa:
    generate-ddl: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
  instance:
    hostname: ${APPLICATION_DOMAIN:http://127.0.0.1:${server.port}}
    nonSecurePort: 80
